version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --explicit-defaults-for-timestamp=1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    #ports:
    #  - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  airflow:
    build: airflow/
    container_name: airflow
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      LOAD_EX: y
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqldb://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      AIRFLOW__CORE__SQL_ENGINE_COLLATION_FOR_IDS: utf8mb3_bin
      MONGO_CLIENT_DB: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/?authSource=admin"
      MONGO_DATABASE: airflow
      MONGO_COLLECTION_OK: standard_ok
      MONGO_COLLECTION_KO: standard_ko
      MONGO_HISTORIC: historic
    ports:
      - "8090:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - data-volume:/data:rw
    command: >
      bash -c "airflow db init && airflow webserver"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 20s
      timeout: 5s
      retries: 4
  
  mongodb:
    image: mongo:8.0.4-noble
    container_name: mongodb
    restart: always
    depends_on:
      airflow:
        condition: service_healthy
    #ports:
    #  - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_db_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

volumes:
  data-volume:
  mysql_data:
  mongo_db_data:
